SELECT
	'2020',
	'T',
	't-' || USERS.dcid,
	NULL,
	USERS.first_name,
	USERS.middle_name,
	USERS.last_name,
	'PK-12',
	USERS.EMAIL_ADDR,
	NULL,
	'MDR',
	NULL,
	USERS.EMAIL_ADDR,
	'ED',
	SCHOOLSTAFF.schoolid

FROM USERS
	JOIN SCHOOLSTAFF ON USERS.dcid = SCHOOLSTAFF.users_dcid
	
WHERE
	SCHOOLSTAFF.staffstatus = 1
	AND SCHOOLSTAFF.schoolid IN (1925,1923,3000,9404,1153,1157,2988,1705,798,2062,1938)
	AND SCHOOLSTAFF.status = 1
	AND USERS.last_name NOT LIKE '%TBA%'
	AND USERS.EMAIL_ADDR IS NOT NULL
	
ORDER BY
	USERS.last_name
